### ISSUE TITLE
[ElmSharp] "Failed to set file to Image" in Weather application

### ISSUE THREAD

**Issue by swift-kim** [Samsung/TizenFX#1688]
A System.InvalidOperationException is thrown occasionally when loading an image from URI in Weather application.

To reproduce:

1. Build https://github.com/Samsung/Tizen-CSharp-Samples/tree/master/Wearable/Weather with your own or temporary API key (`e573dcdc6ebe1641278fea19131ea78d`)
2. Run the app on a device after connecting to a Wi-Fi network
3. Choose [US]-[Austin] from the city list
4. Click [Check Weather]
5. Click [Check Forecast]
6. Turn the rotary wheel clockwise a few time

```
System.InvalidOperationException: Failed to set file to Image
   at ElmSharp.Image.LoadAsync(String file, CancellationToken cancellationToken)
   at Xamarin.Forms.Platform.Tizen.Native.Image.LoadFromImageSourceAsync(ImageSource source)
   at Xamarin.Forms.Platform.Tizen.ImageRenderer.UpdateSource()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
   at Tizen.Applications.TizenSynchronizationContext.<>c__DisplayClass1_0.<Post>b__0()
   at Tizen.Applications.TizenSynchronizationContext.GSourceManager.Handler(IntPtr userData)
   at Tizen.Applications.CoreBackend.UICoreBackend.Run(String[] args)
   at Tizen.Applications.CoreApplication.Run(String[] args)
   at Tizen.Applications.CoreUIApplication.Run(String[] args)
   at Weather.Program.Main(String[] args)
```

The unhandled exception is not caught by anything so it's propagated to TizenSynchronizationContext. The full stacktrace just before calling LoadAsync looks likes this (obtained via lldb):

```
Child SP       IP Call Site
FFB58ED8 EC699FFE ElmSharp.Image.LoadAsync(System.String, System.Threading.CancellationToken)
FFB58F10 EC69A074 ElmSharp.Image.LoadAsync(System.Uri, System.Threading.CancellationToken)
FFB58F28 E42F1E64 Xamarin.Forms.Platform.Tizen.UriImageSourceHandler.LoadImageAsync(Xamarin.Forms.Platform.Tizen.Native.Image, Xamarin.Forms.ImageSource, System.Threading.CancellationToken)
FFB58F40 E42D9A9A Xamarin.Forms.Platform.Tizen.Native.Image+<LoadFromImageSourceAsync>d__5.MoveNext()
FFB58F60 E42D72E8 System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Xamarin.Forms.Platform.Tizen.Native.Image+<LoadFromImageSourceAsync>d__5, Xamarin.Forms.Platform.Tizen]](<LoadFromImageSourceAsync>d__5 ByRef)
FFB58F80 E42DCA90 Xamarin.Forms.Platform.Tizen.Native.Image.LoadFromImageSourceAsync(Xamarin.Forms.ImageSource)
FFB58FA8 E42DA642 Xamarin.Forms.Platform.Tizen.ImageRenderer+<UpdateSource>d__2.MoveNext()
FFB58FC8 E42D7658 System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Xamarin.Forms.Platform.Tizen.ImageRenderer+<UpdateSource>d__2, Xamarin.Forms.Platform.Tizen]](<UpdateSource>d__2 ByRef)
FFB58FE8 E42F19F0 Xamarin.Forms.Platform.Tizen.ImageRenderer.UpdateSource()
FFB59008 E42F1926 Xamarin.Forms.Platform.Tizen.ImageRenderer.OnElementPropertyChanged(System.Object, System.ComponentModel.PropertyChangedEventArgs)
FFB59028 E2E6CBD8 ILStubClass.IL_STUB_SecureDelegate_Invoke(System.Object, System.ComponentModel.PropertyChangedEventArgs)
FFB59030 E3FA2A18 Xamarin.Forms.BindableObject.OnPropertyChanged(System.String)
FFB59040 E3FB60B2 Xamarin.Forms.Element.OnPropertyChanged(System.String)
FFB59068 E3FA3292 Xamarin.Forms.BindableObject.SetValueActual(Xamarin.Forms.BindableProperty, BindablePropertyContext, System.Object, Boolean, Xamarin.Forms.Internals.SetValueFlags, Boolean)
FFB590B0 E3FA3054 Xamarin.Forms.BindableObject.SetValueCore(Xamarin.Forms.BindableProperty, System.Object, Xamarin.Forms.Internals.SetValueFlags, SetValuePrivateFlags)
FFB59108 E3FDC85E Xamarin.Forms.BindingExpression.ApplyCore(System.Object, Xamarin.Forms.BindableObject, Xamarin.Forms.BindableProperty, Boolean)
FFB59158 E3FDC3AC Xamarin.Forms.BindingExpression.Apply(Boolean)
FFB59178 E3FE3C90 Xamarin.Forms.BindingExpression+BindingExpressionPart.<PropertyChanged>b__49_0()
FFB59180 E3FE3B26 Xamarin.Forms.BindingExpression+BindingExpressionPart.PropertyChanged(System.Object, System.ComponentModel.PropertyChangedEventArgs)
FFB591B8 E3FE3E88 Xamarin.Forms.BindingExpression+WeakPropertyChangedProxy.OnPropertyChanged(System.Object, System.ComponentModel.PropertyChangedEventArgs)
FFB591D8 E4437D38 ILStubClass.IL_STUB_MulticastDelegate_Invoke(System.Object, System.ComponentModel.PropertyChangedEventArgs)
FFB591F8 E3FA2A18 Xamarin.Forms.BindableObject.OnPropertyChanged(System.String)
FFB59208 E43CD704 Weather.ViewModels.ForecastViewModel.<PrepareViewModels>b__31_1(System.Object)
FFB59248 E400F98E Xamarin.Forms.Command.Execute(System.Object)
FFB59250 E43CD806 Weather.Views.ForecastPage.Rotate(Tizen.Wearable.CircularUI.Forms.RotaryEventArgs)
FFB59290 E424FB7E Tizen.Wearable.CircularUI.Forms.Renderer.CirclePageRenderer.OnRotaryEventChanged(ElmSharp.Wearable.RotaryEventArgs)
FFB592A8 DF5DA7E6 ElmSharp.Wearable.RotaryEventManager+<>c__DisplayClass2_0.<add_Rotated>b__0(IntPtr, IntPtr)
FFB592E0 DF5DA71E ILStubClass.IL_STUB_ReversePInvoke(Int32, Int32)
FFB5A7B4 f31734f8 [InlinedCallFrame: ffb5a7b4]
FFB5A7B4 e591de90 [InlinedCallFrame: ffb5a7b4] Interop+Application.Main(Int32, System.String[], UIAppLifecycleCallbacks ByRef, IntPtr)
FFB5A7B0 E591DE90 ILStubClass.IL_STUB_PInvoke(Int32, System.String[], UIAppLifecycleCallbacks ByRef, IntPtr)
FFB5A860 E591D760 Tizen.Applications.CoreBackend.UICoreBackend.Run(System.String[])
FFB5A888 E59415D6 Tizen.Applications.CoreApplication.Run(System.String[])
FFB5A8C0 E591D10A Tizen.Applications.CoreUIApplication.Run(System.String[])
FFB5A8E0 E43D5E9E Weather.Program.Main(System.String[])
FFB5AA74 f3173402 [GCFrame: ffb5aa74]
FFB5AE08 f3173402 [GCFrame: ffb5ae08]
```

EFL dlog:
```
E/EFL     ( 5190): <5190> ../src/lib/efl/interfaces/efl_file.c:177 efl_file_simple_load() File set to 'http://openweathermap.org/img/w/03n.png' on 'Efl.Ui.Image_Legacy@0x8004c7e4[1]:(70,105 102x100):children=2' failed.
```

Note that the URI (http://openweathermap.org/img/w/03n.png) passed to the LoadAsync method is not likely the source of the problem.

I couldn't reproduce this with a simple app template instead of Weather application.

**Comment by myroot** [comment]
I reproduce this issue with simple code
``` xml
        <StackLayout Orientation="Vertical">
            <Image x:Name="WeatherIcon"
                    
                    HeightRequest="100"
                    WidthRequest="100"
                    Aspect="AspectFit" />
            <Label
                    Text="Label"
                    HorizontalTextAlignment="Center"
                    VerticalTextAlignment="Center"
                    FontSize="5" />
        </StackLayout>
```
``` c#
            Device.StartTimer(TimeSpan.FromMilliseconds(500), () =>
            {
                WeatherIcon.Source = "http://openweathermap.org/img/w/01n.png";
                return true;
            });
```
[ImageBug.zip](https://github.com/Samsung/TizenFX/files/4767704/ImageBug.zip)

**Comment by myroot** [comment]
It reproducible on Wearable/Mobile 5.5 emulator also but does not reproduce in 4.0 wearable emulator
It must be EFL native issue, but i can't reproduce it with only elmsharp

**Comment by myroot** [comment]
I alos reproduce it with Elmsharp
``` c#

            Image img = new Image(window);
            img.Show();
            box.PackEnd(img);

            box.SetLayoutCallback(() =>
            {
                img.Geometry = new Rect(0, 100, 360, 100);
            });

            Console.WriteLine($"LoadAsync");
            img.LoadAsync(new Uri("http://openweathermap.org/img/w/01n.png"));

            EcoreMainloop.AddTimer(2.0, () =>
            {
                Console.WriteLine($"LoadAsync2");
                Action action = new Action(async () =>
                {
                    var result = await img.LoadAsync(new Uri("http://openweathermap.org/img/w/01n.png"));
                    Console.WriteLine($"Load result : {result}");
                });
                action();
                return true;
            });
```
[ElmSharpTemplate1.zip](https://github.com/Samsung/TizenFX/files/4768154/ElmSharpTemplate1.zip)

**Comment by myroot** [comment]
It was resolved on Native layer
