### ISSUE TITLE
[Tizen.Pims.Calendar] Exceptions occur when using CalendarTime.

### ISSUE THREAD

**Issue by sung-su** [Samsung/TizenFX#2064]
Exceptions occur when using CalendarTime.

case1) UtcTime and LocalTime value are not same after creation.
```
var time1 = new CalendarTime(2012, 12, 14, 23, 0, 0);
var time2 = new CalendarTime(DateTime.Now.Ticks);
```

case 2) exception occurs when inserting the record with containing the CalendarTime.
```
var record = new CalendarRecord(Tizen.Pims.Calendar.CalendarViews.Event.Uri);
var time = new CalendarTime(DateTime.Now.Ticks);
record.Set<CalendarTime>(TCalendarViews.Event.Start, time);
var item = manager.Database.Insert(record);
```
```
09-30 02:38:16.126+0900 I/DOTNET_LAUNCHER( 6630): convert calendar
09-30 02:38:16.130+0900 I/DOTNET_LAUNCHER( 6630): Unhandled exception.
09-30 02:38:16.131+0900 I/DOTNET_LAUNCHER( 6630):  
09-30 02:38:16.179+0900 I/DOTNET_LAUNCHER( 6630): System.ArgumentException: Invalid parameter
   at Tizen.Pims.Calendar.CalendarDatabase.Insert(CalendarRecord record)
   at CrossTemplate2.App.CreateEvent() in Z:\github\xamarin-forms-apps\FormsTizenGallery\CrossTemplate2\CrossTemplate2.Tizen\CrossTemplate2.cs:line 115
   at CrossTemplate2.App.<.ctor>b__1_1(Object s, EventArgs e) in Z:\github\xamarin-forms-apps\FormsTizenGallery\CrossTemplate2\CrossTemplate2.Tizen\CrossTemplate2.cs:line 41
   at Xamarin.Forms.Button.Xamarin.Forms.Internals.IButtonElement.PropagateUpClicked()
   at Xamarin.Forms.ButtonElement.ElementClicked(VisualElement visualElement, IButtonElement ButtonElementManager)
   at Xamarin.Forms.Button.SendClicked()
   at Xamarin.Forms.Platform.Tizen.ButtonRenderer.OnButtON-CLICKed(Object sender, EventArgs e)
   at ElmSharp.Button.<.ctor>b__4_0(Object sender, EventArgs e)
   at ElmSharp.SmartEvent.SendEvent(Object sender, EventArgs e)
   at ElmSharp.SmartEvent`1.<>c__DisplayClass12_0.<add_On>b__0(IntPtr d, IntPtr o, IntPtr e)
   at Tizen.Applicatio
09-30 02:38:16.179+0900 I/DOTNET_LAUNCHER( 6630): ns.CoreBackend.UICoreBackend.Run(String[] args)
   at Tizen.Applications.CoreApplication.Run(String[] args)
   at Tizen.Applications.CoreUIApplication.Run(String[] args)
   at CrossTemplate2.Program.Main(String[] args) in Z:\github\xamarin-forms-apps\FormsTizenGallery\CrossTemplate2\CrossTemplate2.Tizen\CrossTemplate2.Tizen.cs:line 19
09-30 02:38:16.179+0900 I/DOTNET_LAUNCHER( 6630): DLOG_ERROR_NOMSG
09-30 02:38:16.179+0900 I/DOTNET_LAUNCHER( 6630): onSigabrt called
```
 
case 3) exception occurs when querying the CalendarTime.
```
var time = new CalendarTime(2012, 12, 14, 23, 0, 0);
var query = new CalendarQuery(TCalendarViews.Event.Uri);
var filter = new CalendarFilter(TCalendarViews.Event.Uri,
     TCalendarViews.Event.Start,
     CalendarFilter.IntegerMatchType.Equal,
     time);
query.SetFilter(filter);
var list = manager.Database.GetRecordsWithQuery(query, 0, 0);
```
```
09-30 02:47:50.795+0900 I/DOTNET_LAUNCHER( 9263):  #### get all list: 9
09-30 02:47:50.854+0900 I/DOTNET_LAUNCHER( 9263):  #### id=1, summary=Updated event summary, description=Updated event description, time(UTC)=6/29/2014 10:03:20 AM, time(Local)=1/1/0001 12:00:00 AM
09-30 02:47:50.854+0900 I/DOTNET_LAUNCHER( 9263):  #### id=2, summary=A recurring event, description=Recurring event description, time(UTC)=12/14/2012 11:00:00 PM, time(Local)=1/1/0001 12:00:00 AM
09-30 02:47:50.854+0900 I/DOTNET_LAUNCHER( 9263):  #### id=3, summary=A recurring event, description=Recurring event description, time(UTC)=12/14/2012 11:00:00 PM, time(Local)=1/1/0001 12:00:00 AM
09-30 02:47:50.854+0900 I/DOTNET_LAUNCHER( 9263):  #### id=4, summary=Updated event summary, description=Updated event description, time(UTC)=6/29/2014 10:03:20 AM, time(Local)=1/1/0001 12:00:00 AM
09-30 02:47:50.854+0900 I/DOTNET_LAUNCHER( 9263):  #### id=5, summary=A recurring event, description=Recurring event description, time(UTC)=12/14/2012 11:00:00 PM, time(Local)=1/1/0001 12:00:00 AM
09-30 02:47:50.854+0900 I/DOTNET_LAUNCHER( 9263):  #### id=6, summary=A recurring event, description=Recurring event description, time(UTC)=12/14/2012 11:00:00 PM, time(Local)=1/1/0001 12:00:00 AM
 #### id=7, summary=Updated event summary, description=Updated event description, time(UTC)=6/29/2014 10:03:20 AM, time(Local)=1/1/0001 12:00:00 AM
09-30 02:47:50.854+0900 I/DOTNET_LAUNCHER( 9263):  #### id=8, summary=A recurring event, description=Recurring event description, time(UTC)=12/14/2012 11:00:00 PM, time(Local)=1/1/0001 12:00:00 AM
 #### id=9, summary=A recurring event, description=Recurring event description, time(UTC)=12/14/2012 11:00:00 PM, time(Local)=1/1/0001 12:00:00 AM

09-30 02:47:55.783+0900 I/DOTNET_LAUNCHER( 9263): convert calendar
09-30 02:47:55.784+0900 I/DOTNET_LAUNCHER( 9263):  ##### time(UTC)=1/1/0001 12:00:00 AM, time(Local)=12/14/2012 11:00:00 PM
09-30 02:47:55.784+0900 I/DOTNET_LAUNCHER( 9263): 
(process:9263): GLib-CRITICAL **: 02:47:55.784: g_variant_new_variant: assertion 'value != NULL' failed
``` 

test  code
```
using System;
using Tizen.Pims.Calendar;
using Tizen.Security;
using Xamarin.Forms;
using TCalendarViews = Tizen.Pims.Calendar.CalendarViews;

namespace CrossTemplate2
{
    public class App : Application
    {
        CalendarManager manager;

        public App()
        {
            var readPrivilege = "http://tizen.org/privilege/calendar.read";
            var writePrivilege = "http://tizen.org/privilege/calendar.write";

            PrivacyPrivilegeManager.RequestPermission(readPrivilege);
            PrivacyPrivilegeManager.RequestPermission(writePrivilege);

            PrivacyPrivilegeManager.ResponseContext context = null;
            if (PrivacyPrivilegeManager.GetResponseContext(writePrivilege).TryGetTarget(out context))
            {
                context.ResponseFetched += (s, e) =>
                {
                    manager = new CalendarManager();
                    Console.WriteLine($" Init Calendar Manager");
                };
            }

            var button = new Button
            {
                HorizontalOptions = LayoutOptions.FillAndExpand,
                Text = "add event"
            };

            button.Clicked += (s, e) =>
            {
                CreateEvent();
            };

            var getAllButton = new Button
            {
                HorizontalOptions = LayoutOptions.FillAndExpand,
                Text = "get all"
            };

            getAllButton.Clicked += (s, e) =>
            {
                GetAllEvent();
            };

            var getButton = new Button
            {
                HorizontalOptions = LayoutOptions.FillAndExpand,
                Text = "get with filter(string)"
            };

            getButton.Clicked += (s, e) =>
            {
                GetEvent();
            };

            var getButton2 = new Button
            {
                HorizontalOptions = LayoutOptions.FillAndExpand,
                Text = "get with filter(time)"
            };

            getButton2.Clicked += (s, e) =>
            {
                GetEvent2();
            };

            // The root page of your application
            MainPage = new ContentPage
            {
                Content = new StackLayout
                {
                    VerticalOptions = LayoutOptions.Center,
                    Children = {
                        new Label {
                            HorizontalTextAlignment = TextAlignment.Center,
                            Text = "Welcome to Xamarin Forms!"
                        },
                        button,
                        getAllButton,
                        getButton,
                        getButton2
                    }
                }
            };
        }

        public void CreateEvent()
        {
            var version = manager.Database.Version;
            Console.WriteLine($" ############## calendar version = {version}");

            var record = new CalendarRecord(Tizen.Pims.Calendar.CalendarViews.Event.Uri);
            record.Set<string>(TCalendarViews.Event.Summary, "Test");

            var time = new CalendarTime(DateTime.Now.Ticks);
            record.Set<CalendarTime>(TCalendarViews.Event.Start, time);
            record.Set<string>(TCalendarViews.Event.StartTzid, "Asia/Seoul");
            record.Set<string>(TCalendarViews.Event.Description, "Test event");

            var id = manager.Database.Insert(record);

            Console.WriteLine($" #### event added: {id}, time={time}, description=Test event");
        }

        public void GetAllEvent()
        {
            var list = manager.Database.GetAll(TCalendarViews.Event.Uri, 0, 0);
            Console.WriteLine($" #### get all list: {list.Count}");
            PrintList(list);
        }

        void PrintList (CalendarList list)
        {
            if (list.Count < 1)
                return;

            list.MoveFirst();
            var record = list.GetCurrentRecord();

            while (record != null)
            {
                var id = record.Get<int>(TCalendarViews.Event.Id);
                var summary = record.Get<string>(TCalendarViews.Event.Summary);
                var description = record.Get<string>(TCalendarViews.Event.Description);
                var time = record.Get<CalendarTime>(TCalendarViews.Event.Start);

                Console.WriteLine($" #### id={id}, summary={summary}, description={description}, time(UTC)={time.UtcTime}, time(Local)={time.LocalTime}");

                if (list.MoveNext())
                    record = list.GetCurrentRecord();
                else
                    break;
            }
        }

        public void GetEvent()
        {
            var query = new CalendarQuery(TCalendarViews.Event.Uri);
            var filter = new CalendarFilter(TCalendarViews.Event.Uri, 
                TCalendarViews.Event.Summary, 
                CalendarFilter.StringMatchType.Contains, 
                "event");
            filter.AddCondition(CalendarFilter.LogicalOperator.And, 
                TCalendarViews.Event.Description, 
                CalendarFilter.StringMatchType.Contains, 
                "Test");

            query.SetFilter(filter);
            var list = manager.Database.GetRecordsWithQuery(query, 0, 0);
            Console.WriteLine($" ##### result list = {list.Count}");
            PrintList(list);
        }

        public void GetEvent2()
        {
            var time = new CalendarTime(2012, 12, 14, 23, 0, 0);

            var query = new CalendarQuery(TCalendarViews.Event.Uri);
            var filter = new CalendarFilter(TCalendarViews.Event.Uri,
                TCalendarViews.Event.Start,
                CalendarFilter.IntegerMatchType.Equal,
                time);

            query.SetFilter(filter);
            Console.WriteLine($" ##### time(UTC)={time.UtcTime}, time(Local)={time.LocalTime}");
            var list = manager.Database.GetRecordsWithQuery(query, 0, 0);
            Console.WriteLine($" ##### result list = {list.Count}");
            PrintList(list);
        }

        protected override void ON-START()
        {
            // Handle when your app starts
        }

        protected override void OnSleep()
        {
            // Handle when your app sleeps
        }

        protected override void ON-RESUME()
        {
            // Handle when your app resumes
        }
    }
}
```

**Comment by chauhan321** [comment]
Ok Mr. @sung-su  , we are working on it

**Comment by sung-su** [comment]
@randeepsingh01  @chauhan321  any update ?

**Comment by chauhan321** [comment]
We were busy in M2 release and now due to covid i have been given Work in home (working with SVPN)
SRID IT team is working on syncing SLAM security with Escort for SVPN devices.(due to this Visual studio not installed on my system)
Please wait for 1 week.

**Comment by sung-su** [comment]
@chauhan321 I'm waiting for your reply. when will it be fixed?

**Comment by chauhan321** [comment]
I have got access to visual studio, i am working on the issue, you will get the solution by this week.
