### ISSUE TITLE
Question/Possible bug after update to Tizen 5.5

### ISSUE THREAD

**Issue by SHuygh** [Samsung/TizenFX#2793]
We have a b2b application which runs on the Galaxy watch. 
After updating the watch from 4.0.07 to 5.5.0.1, our application crashes due to not being able to setup a bluetooth socket connection to a bonded device. We get the following exception and stack trace. As it is not possible to rollback the devices to a previous Tizen version this is a blocking issue for us.
It might be related to the Android OS version of the phone the watch is connected to as for now it seems that watches connected to Android 10 devices (All Samsung Galaxy A6) are impacted.

Do you have any suggestions of how to work around/fix this issue? The address we pass is also obtained through the BluetoothAdapter

"exception" : "NullReferenceException Object reference not set to an instance of an object.",

"stackTrace" : "at System.SpanHelpers.IndexOf(Byte& searchSpace, Byte value, Int32 length)
at System.String.Ctor(SByte* value)
at System.Runtime.InteropServices.Marshal.PtrToStringAnsi(IntPtr ptr)
at Tizen.Network.Bluetooth.BluetoothUtils.ConvertStructToDeviceClass(BluetoothDeviceStruct device)
at Tizen.Network.Bluetooth.BluetoothAdapterImpl.GetBondedDevice(String address)

**Comment by SHuygh** [comment]
I noticed that the following PR fixes that exception.
https://github.com/Samsung/TizenFX/pull/2514

However, as it is not available on older API levels this does not immediately fix the problem. Would it be possible to release a new version with this as a hot fix, as there isn't any backwards compatibility on the API levels
